apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-nginx
  namespace: demo
  labels:
    app: demo-app
data:
  default.conf: |
    server {
        listen 80;
        root /data;
        autoindex on;

        location / {
            try_files $uri $uri/ =404;
        }
    }